# Generated by Django 4.0.3 on 2022-04-04 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventbrite_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventbrite_id', models.CharField(blank=True, max_length=16)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.URLField(blank=True, max_length=500)),
                ('created_user', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='main_app.tag')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('venue', models.ManyToManyField(to='main_app.venue')),
            ],
        ),
    ]
