# Generated by Django 4.0.3 on 2022-04-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_created_by_event_created_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_user',
            new_name='created_by',
        ),
    ]
