# Generated by Django 4.0.3 on 2022-04-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_user'),
        ('main_app', '0003_venue_city'),
    ]

    operations = [
    ]
