# Generated by Django 4.0.3 on 2022-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_colors_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='colors',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.JSONField(default={'color': ['red', 'blue']}),
        ),
    ]
