# Generated by Django 4.0.3 on 2022-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_event_colors_event_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.ManyToManyField(to='main_app.color'),
        ),
    ]
