# Generated by Django 4.0.3 on 2022-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventbrite_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
