# Generated by Django 4.0.3 on 2022-04-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_event_color_event_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
