# Generated by Django 4.0.3 on 2022-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_event_color_event_color_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='main_app/images'),
        ),
    ]
